### ISSUE TITLE
Parameters are empty if request is Content-Type: application/json

### ISSUE THREAD

**Issue by nbulaj** [ridiculous/grape-middleware-logger#11]
Hi. If you will try to make a request with JSON body and `Content-Type: application/json` then logger will write an empty parameters to the log:

> I, [2016-09-15T10:59:30.005328 #27381]  INFO -- : [e323e78c-9627-4be5-b236-fe607ae9fb7f] Started POST "/api/v1/users" at 2016-09-15 10:59:30 +0000
> I, [2016-09-15T10:59:30.005382 #27381]  INFO -- : [e323e78c-9627-4be5-b236-fe607ae9fb7f] Processing by V1::Users/users/
> I, [2016-09-15T10:59:30.005435 #27381]  INFO -- : [e323e78c-9627-4be5-b236-fe607ae9fb7f]   Parameters: {}

I think it is a bug.

**Comment by nbulaj** [comment]
The problem was solved by changing `use Grape::Middleware::Logger` to `insert_after Grape::Middleware::Formatter, Grape::Middleware::Logger` (as described in README).

I think that such a change had to be described in the gem post-install message so the developers could fix the problem after update.

Closing issue.

**Comment by ridiculous** [comment]
Thanks, good point about the post install message 👍 Didn't think about that
