### ISSUE TITLE
Redundant log when using Rails + Grape

### ISSUE THREAD

**Issue by marceloboeira** [ridiculous/grape-middleware-logger#2]
Using Rails + Grape causes duplicated entries on the log.

`2015-10-23 09:03:15 [web]: Started GET "/api/videos/a37b29df2/" for 10.24.40.84 at 2015-10-23 09:03:15 -0200`
`2015-10-23 09:03:15 [web]: Started GET "/api/videos/a37b29df2/"`
`2015-10-23 09:03:15 [web]: Parameters: {"video_id"=>"a37b29df2"}`

I believe this is caused by then both together, since they don't know about each other. 
Rails or Rack must be logging the incoming request because of the router and Grape logs it again...

**Comment by ridiculous** [comment]
Yeah, I had the same problem. The workaround I used was selectively calling the Rails logger when requesting a non-api route. For example:
```ruby
# config/application.rb
config.middleware.delete 'Rails::Rack::Logger'
config.middleware.insert_after 'ActionDispatch::RequestId', 'SelectiveLogger'

# config/initializers/selective_logger.rb
class SelectiveLogger
  def initialize(app)
    @app = app
  end

  def call(env)
    if env['PATH_INFO'] =~ %r{^/api}
      @app.call(env)
    else
      Rails::Rack::Logger.new(@app).call(env)
    end
  end
end
```
It's probably possible to incorporate that into the gem using a Railtie, just never tried it.

**Comment by marceloboeira** [comment]
@ridiculous awesome, thanks. I'm not really sure if this gem should cover this.

**Comment by ridiculous** [comment]
:+1:
