### ISSUE TITLE
logging 404s

### ISSUE THREAD

**Issue by skandragon** [ridiculous/grape-middleware-logger#20]
It doesn't appear requests that return 404s are logged.  Is there an option I can use to enable these, or is this difficult since there is no catch-all route to hook into?

**Comment by ridiculous** [comment]
I think this can't currently be done with this middlewar, since grape intercepts farther upstream

**Comment by ridiculous** [comment]
I've had to do this tho to work with 404s:
```ruby
class API < Grape::API
  cascade false # Prevents unfound routes from rendering 404 page
  use Grape::Middleware::Logger
end
```
in case it helps
