### ISSUE TITLE
filter out specific paths

### ISSUE THREAD

**Issue by skandragon** [ridiculous/grape-middleware-logger#21]
It would be helpful to have a way to filter out paths from logging.

In my case, we have a /healthcheck that is hit about once every second to verify that the service is up from our load balancer's viewpoint.  This is logged along with all other requests, and it would be nice to have a way to ignore this.

I see ways to filter based on params, but I don't think that works for this use case.

I may dive in and see if I can come up with a way that is clean enough as well; if I do I'll submit a PR.

**Comment by ridiculous** [comment]
open to a PR
