### ISSUE TITLE
Reorders I18n.load_path

### ISSUE THREAD

**Issue by leoarnold** [ridiculous/grape-middleware-logger#24]
Adding the initializer after `:load_config_initializers` reorders the `I18n.load_path` (rails-i18n), giving the default translations from the gem higher priority than my modifications in `config/locales`.

I have no clue why this is happening, but when I remove the `after: :load_config_initializers` from the Railtie, everything is normal again.

To emphasize: It seems to be about the position of this gems' initializer, _not_ about what the initializer actually does.

Moreover, inspecting `MyApp::Application.instance.initializers.map(&:name)` lists `grape.middlware.logger` actually **before** `load_config_initializers`.

**Comment by ridiculous** [comment]
Does the logger and filtered_params get copied correctly from the rails app if we remove the `after: ` option? If so, we don't need it. I think I added it because otherwise the logger was nil

**Comment by ridiculous** [comment]
I see why it's like this: `Rails.application.config.filter_parameters` isn't set until load_config_initializers step, at least for older Rails versions (<5). It seems to work fine for Rails 5 without the order specified. Fixed on master and will cut a release soon

**Comment by ridiculous** [comment]
Fixed in v1.11.0
