### ISSUE TITLE
Parameters is empty

### ISSUE THREAD

**Issue by numbcoder** [ridiculous/grape-middleware-logger#4]
Parameters is an empty hash when post with json, but the `params` is correct

```http
POST /posts HTTP/1.1
Content-Type: application/json
Host: localhost:3000
Connection: close
User-Agent: Paw/2.3.2 (Macintosh; OS X/10.11.4) GCDHTTPRequest
Content-Length: 17

{"title":"hello"}
```
```curl
curl -X "POST" "http://localhost:3000/posts" \
	-H "Content-Type: application/json" \
	-d "{\"title\":\"hello\"}"
```
```log
Started POST "/posts" at 2016-03-30 17:02:17 +0800
Processing by PostsApi#posts
  Parameters: {}
Completed 500 in 1.05ms
```

**Comment by ridiculous** [comment]
I was able to reproduce using the https://github.com/ruby-grape/grape-on-rack example using Grape (v0.14.0). Not sure what's going on yet. I swear it used to work ...

**Comment by ridiculous** [comment]
What version of Grape and Ruby are you using?

**Comment by numbcoder** [comment]
Grape 0.15.0
Ruby 2.3.0

**Comment by ridiculous** [comment]
You wanna try the latest master and see if it's fixed for you? If it is, I'll cut a new gem version with the changes.

**Comment by numbcoder** [comment]
works in this commit https://github.com/ridiculous/grape-middleware-logger/commit/41eeaaaeabefa66dbfb5b9c699d4c2afc6fe4955, but master is not work

`request_params` can get from `env[Grape::Env::RACK_REQUEST_FORM_HASH]` https://github.com/ridiculous/grape-middleware-logger/commit/41eeaaaeabefa66dbfb5b9c699d4c2afc6fe4955#diff-d37acfdf2e7dc7daf14345bf49cc9b79R89

My project stack: Rails 5.0.0.beta3 + Grape 0.15.0

**Comment by ridiculous** [comment]
Oh your using this with Rails?! We should be getting the params from `env['action_dispatch.request.request_parameters']` ... I haven't tested it with Rails 5, maybe they changed the env key. Are you requiring rails in your Gemfile before grape-middleware-logger?

**Comment by ridiculous** [comment]
I added back the functionality present in https://github.com/ridiculous/grape-middleware-logger/commit/41eeaaaeabefa66dbfb5b9c699d4c2afc6fe4955. You want to try the latest master now? 6c2559c8ec86e7aa3bcec8c6aaea9bcf613e3da7

**Comment by numbcoder** [comment]
works!
