### ISSUE TITLE
Need Changelog.md

### ISSUE THREAD

**Issue by Edison-Hsu** [ridiculous/grape-middleware-logger#5]
I really like this project, but I found that JSON parameters is empty when I using version 1.5.1 and grape v0.14.0
So I want to know changes between v1.5.1 and v1.6. What if v1.6 fixed this issue, all I need to do is `bundle update`.
Could you provide a CHANGELOG.md file or CHANGELOG section in README.md

Thanks

**Comment by ridiculous** [comment]
Yeah, I've been planning on adding that going forward, because they are super helpful. For now you can see the diff between v1.5.1 and 1.6 here: https://github.com/ridiculous/grape-middleware-logger/compare/v1.5.1...master

And yes, that issue was fixed in 1.6
