### ISSUE TITLE
rack app

### ISSUE THREAD

**Issue by MeterSoft** [ridiculous/grape-middleware-logger#8]
/home/meter/.rvm/gems/ruby-1.9.3-p551-falcon/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- grape/middleware/globals (LoadError)
	from /home/meter/.rvm/gems/ruby-1.9.3-p551-falcon/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/meter/.rvm/gems/ruby-1.9.3-p551-falcon/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/meter/.rvm/gems/ruby-1.9.3-p551-falcon/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/meter/.rvm/gems/ruby-1.9.3-p551-falcon/gems/grape-middleware-logger-0.1.2/lib/grape/middleware/logger.rb:2:in `<top (required)>'
	from /home/meter/.rvm/gems/ruby-1.9.3-p551-falcon/gems/bundler-1.11.2/lib/bundler/runtime.rb:91:in `require'
	from /home/meter/.rvm/gems/ruby-1.9.3-p551-falcon/gems/bundler-1.11.2/lib/bundler/runtime.rb:91:in `rescue in block in require'
	from /home/meter/.rvm/gems/ruby-1.9.3-p551-falcon/gems/bundler-1.11.2/lib/bundler/runtime.rb:68:in `block in require'
	from /home/meter/.rvm/gems/ruby-1.9.3-p551-falcon/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
	from /home/meter/.rvm/gems/ruby-1.9.3-p551-falcon/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
	from /home/meter/.rvm/gems/ruby-1.9.3-p551-falcon/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
	from /home/meter/work/infocus_rake_api/config/application.rb:10:in `<top (required)>'
	from /home/meter/work/infocus_rake_api/config/environment.rb:3:in `require'
	from /home/meter/work/infocus_rake_api/config/environment.rb:3:in `<top (required)>'
	from /home/meter/work/infocus_rake_api/config.ru:1:in `require'
	from /home/meter/work/infocus_rake_api/config.ru:1:in `block in <main>'
	from /home/meter/.rvm/gems/ruby-1.9.3-p551-falcon/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /home/meter/.rvm/gems/ruby-1.9.3-p551-falcon/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from /home/meter/work/infocus_rake_api/config.ru:in `new'
	from /home/meter/work/infocus_rake_api/config.ru:in `<main>'

**Comment by ridiculous** [comment]
@MeterSoft OK ... what's you're Gemfile look like? Might be an ordering problem. Make sure Grape is required before the this gem.

**Comment by ridiculous** [comment]
And I see you're using an older version of the logger. Can you upgrade to a newer version?

**Comment by ridiculous** [comment]
Closing due to no response
